config/routes.rb
Rails.application.routes.draw do
   

  namespace :api do
    namespace :v1 do
      resources :apps
    end
  end

  # devise_for :users
  # devise_for :users, controllers: { registrations: 'users/registrations'}
  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}

  resources :apps
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'apps#index'

  devise_scope :user do
    get 'sign_in', to: 'devise/sessions#new'
    get 'sign_up', to: 'devise/registrations#new'
    get 'log_out', to: 'devise/sessions#destroy'
  end
end

app/views/pages/account.html.erb
<%= javascript_pack_tag 'account_js' %>
<% if @current_user %>
<h1><%=@current_user.email %></h1>
<%= link_to "home", :root, class: "item" %>
<%= link_to "Edit your account", "/pages/account", class: "item" %>
<%= link_to "logout", ENV['OKTA_URL'] + "/login/signout?fromURI=http://localhost:3000/sessions/destroy", class: "item" %>
<% else %>
<%= link_to 'Sign in via Okta', user_oktaoauth_omniauth_authorize_path, method: :post %>
<% end %>

<form id="accountForm">
     <h1>Your Favorite Gemstone </h1>

    <fieldset>
        <input type="text" id="gemname" name="gemname" />
    </fieldset>
    <input type="submit" value="submit"></input>
</form>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>
<% if @current_user %>
  <h1><%=@current_user.email %></h1>
  <%= link_to "Edit your account", "/pages/account", class: "item" %>
  <%#= link_to "logout", ENV['OKTA_URL'] + "/login/signout?fromURI=http://localhost:3000/sessions/destroy", class: "item" %>
  <%= link_to "logout", sessions_destroy_path, class: "item" %>
<% else %>
  <%= link_to 'Sign in via Okta', user_oktaoauth_omniauth_authorize_path, method: :post %>
<% end %>