config/routes.rb
Rails.application.routes.draw do
   

  namespace :api do
    namespace :v1 do
      resources :apps
    end
  end

  # devise_for :users
  # devise_for :users, controllers: { registrations: 'users/registrations'}
  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}

  resources :apps
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'apps#index'

  devise_scope :user do
    get 'sign_in', to: 'devise/sessions#new'
    get 'sign_up', to: 'devise/registrations#new'
    get 'log_out', to: 'devise/sessions#destroy'
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!--
    <meta name="google-signin-client_id" content="<%= ENV["GOOGLE_CLIENT_ID"]%>">
    <script src="https://apis.google.com/js/platform.js" async defer></script>
    -->

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%# if user_signed_in? %>
      <%#= image_tag session[:user_image] %>
      <%#= session[:user_name] %>
      <%#= link_to "Log out", log_out_path %>
    <%# else %>
      <%#= link_to "Sign up", sign_up_path %>
      <%#= link_to "Login", sign_in_path %>
    <%# end %>
    <%= yield %>
  </body>
</html>

app/views/layouts/pdf.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content="text/html; charset=UTF-8" http-equiv="Content-Type"/>
    <%= wicked_pdf_stylesheet_link_tag "pdf" %>
    <%= wicked_pdf_javascript_include_tag "number_pages" %>
  </head>
  <body onload="number_pages">
    <div id="header">
      <!--= wicked_pdf_image_tag 'thumbnail.png', height: "30", width: "auto"-->
    </div>
    <div id="content">
      <%= yield %>
    </div>
  </body>
</html>